export const LOAD_USERS = 'USERS/LOAD_USERS';
export const LOADING_USERS = 'USERS/LOADING_USERS';
export const LOADING_USERS_ERROR = 'USERS/LOADING_USERS_ERROR';
export const LOAD_POSTS = 'POSTS/LOAD_POSTS';
export const LOGIN_IN = 'LOGIN_FORM/LOGIN_IN';
export const LOGIN_IN_ERROR = 'LOGIN_FORM/LOGIN_IN_ERROR';
